Currency error instead of unit
pontem-network/pontem pull request #156
Opened 2021-12-08 15:10 UTC by tikhono

2021-12-08 15:49 UTC, borispovod requested changes

2021-12-08 15:49 UTC, borispovod commented on primitives/src/currency.rs
> +        write!(f, "CurrencyConversionError is here!")
? :) 
let's write conscious error

2021-12-08 15:49 UTC, borispovod commented on primitives/src/currency.rs
> +        write!(f, "CurrencyConversionError is here!")
e.g.: ("can't convert {} to currency", symbol)

2021-12-08 15:49 UTC, borispovod commented on primitives/src/currency.rs
> +        write!(f, "CurrencyConversionError is here!")
or ("unknown currency {}", symbol)

2021-12-09 06:25 UTC, fzzr- commented on .gitignore
> +.idea/
Imho that's should be in your global ignore-config.

2021-12-09 10:07 UTC, fzzr- approved these changes

2021-12-09 17:36 UTC, borispovod approved these changes

2021-12-09 17:37 UTC, merged